# Generated by Django 5.0.1 on 2024-05-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Region',
            fields=[
                ('REG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('REG_Descr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'HR_Region',
                'managed': True,
            },
        ),
    ]
