# Generated by Django 5.0.1 on 2024-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDescription',
            fields=[
                ('FormID', models.AutoField(primary_key=True, serialize=False)),
                ('FormDescr', models.CharField(max_length=50)),
                ('ModuleID', models.CharField(max_length=3)),
                ('MnuID', models.CharField(max_length=3)),
                ('MnuDescr', models.CharField(max_length=50)),
                ('ModuleDescr', models.CharField(max_length=50)),
                ('MnuSubID', models.CharField(max_length=2)),
                ('MnuSubDescr', models.CharField(max_length=50)),
                ('FormSeq', models.CharField(max_length=5)),
                ('FormType', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FormDescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupOfCompanies',
            fields=[
                ('CoID', models.AutoField(primary_key=True, serialize=False)),
                ('CoName', models.CharField(max_length=50)),
                ('Server_Name', models.CharField(max_length=50)),
                ('DB_Name', models.CharField(max_length=20)),
                ('db_UserName', models.CharField(max_length=50)),
                ('db_Password', models.CharField(max_length=50)),
                ('Active', models.BooleanField()),
                ('CoImage', models.CharField(max_length=50)),
                ('CoColor', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'GroupOfCompanies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_Froms',
            fields=[
                ('UF_ID', models.AutoField(primary_key=True, serialize=False)),
                ('COID', models.IntegerField()),
                ('ModuleID', models.IntegerField()),
                ('MnuID', models.IntegerField()),
                ('MnuSubID', models.IntegerField()),
                ('FormSeq', models.IntegerField()),
                ('FormStatusID', models.IntegerField()),
                ('FormStatus', models.CharField(max_length=2)),
                ('Status', models.BooleanField()),
            ],
            options={
                'db_table': 'User_Forms',
                'managed': False,
            },
        ),
    ]
