# Generated by Django 5.0.1 on 2024-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Emp_Sal_Update_Dtl',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('Element_Type', models.CharField(max_length=10)),
                ('Element_Category', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'HR_Emp_Sal_Update_Dtl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HR_Emp_Sal_Update_Mstr',
            fields=[
                ('Emp_Up_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Emp_Up_Date', models.DateTimeField(auto_now_add=True)),
                ('Emp_Category', models.CharField(max_length=100)),
                ('Marital_Status', models.CharField(max_length=50)),
                ('No_of_Children', models.IntegerField()),
                ('Co_ID', models.IntegerField()),
                ('GrossSalary', models.FloatField()),
                ('Remarks', models.CharField(max_length=200)),
                ('HR_Emp_ID', models.IntegerField()),
            ],
            options={
                'db_table': 'HR_Emp_Sal_Update_Mstr',
                'managed': False,
            },
        ),
    ]
