# Generated by Django 5.0.1 on 2024-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HR_W_All_Ded_Department',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('W_All_Ded_ID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'HR_W_All_Ded_Department',
                'managed': False,
            },
        ),
    ]
