# Generated by Django 5.0.1 on 2024-05-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Emp_Monthly_Sal_Mstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalMonth', models.CharField(max_length=2)),
                ('SalYear', models.CharField(max_length=4)),
                ('MDAYS', models.IntegerField()),
                ('WDAYS', models.IntegerField()),
                ('DDAYS', models.IntegerField()),
                ('SAL_CLOSED', models.BooleanField(default=False)),
                ('Remarks', models.CharField(max_length=250)),
                ('GrossSalary', models.FloatField()),
                ('Emp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.hr_employees')),
            ],
            options={
                'db_table': 'HR_Emp_Monthly_Sal_Mstr',
                'managed': True,
            },
        ),
    ]
