# Generated by Django 5.0.1 on 2024-05-07 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '__first__'),
        ('monthly_sal_process', '0001_initial'),
        ('payroll_element', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Emp_Monthly_Sal_Dtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cal_Type', models.CharField(max_length=50)),
                ('Cal_Value', models.FloatField()),
                ('Amount', models.FloatField()),
                ('Element_ID', models.ForeignKey(db_column='Element_ID', on_delete=django.db.models.deletion.CASCADE, to='payroll_element.hr_payroll_elements')),
                ('Emp_ID', models.ForeignKey(db_column='Emp_ID', on_delete=django.db.models.deletion.CASCADE, to='employee.hr_employees')),
                ('Emp_Up_ID', models.ForeignKey(db_column='Emp_Up_ID', on_delete=django.db.models.deletion.CASCADE, to='monthly_sal_process.hr_emp_monthly_sal_mstr')),
            ],
            options={
                'db_table': 'HR_Emp_Monthly_Sal_Dtl',
                'managed': True,
            },
        ),
    ]
