# Generated by Django 5.0.1 on 2024-05-02 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_Emp_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('User_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('User_Password', models.CharField(blank=True, max_length=50, null=True)),
                ('User_Post', models.CharField(blank=True, max_length=200, null=True)),
                ('User_NICNo', models.CharField(blank=True, max_length=50, null=True)),
                ('User_TelNo', models.CharField(blank=True, max_length=50, null=True)),
                ('User_CellNo', models.CharField(blank=True, max_length=50, null=True)),
                ('User_Email', models.CharField(blank=True, max_length=50, null=True)),
                ('User_Status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User_Login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Emp_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('User_Post', models.CharField(blank=True, max_length=200, null=True)),
                ('User_NICNo', models.CharField(blank=True, max_length=50, null=True)),
                ('User_TelNo', models.CharField(blank=True, max_length=50, null=True)),
                ('User_CellNo', models.CharField(blank=True, max_length=50, null=True)),
                ('Emp_ID', models.ForeignKey(blank=True, db_column='Emp_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.hr_employees')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Profile',
                'managed': True,
            },
        ),
    ]
