# Generated by Django 5.0.1 on 2024-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_Emp_Code', models.CharField(blank=True, max_length=10)),
                ('User_Name', models.CharField(blank=True, max_length=200)),
                ('User_Password', models.CharField(blank=True, max_length=50)),
                ('User_Post', models.CharField(blank=True, max_length=200, null=True)),
                ('User_NICNo', models.CharField(blank=True, max_length=50, null=True)),
                ('User_TelNo', models.CharField(blank=True, max_length=50, null=True)),
                ('User_CellNo', models.CharField(blank=True, max_length=50, null=True)),
                ('User_Email', models.CharField(blank=True, max_length=50, null=True)),
                ('User_Status', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'User_Login',
                'managed': False,
            },
        ),
    ]
