# Generated by Django 5.0.1 on 2024-05-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_login', '0002_remove_user_profile_user_emp_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
