# Generated by Django 5.0.1 on 2024-05-06 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '__first__'),
        ('hr_login', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Emp_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.hr_employees'),
        ),
    ]
