# Generated by Django 5.0.1 on 2024-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Loans',
            fields=[
                ('Loan_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Loan_Date', models.DateTimeField()),
                ('Loan_Type', models.CharField(max_length=30)),
                ('Loan_Amount', models.FloatField()),
                ('Loan_Ded_Amt', models.FloatField()),
                ('Loan_Ded_NoofMnth', models.FloatField()),
                ('Remarks', models.CharField(max_length=50)),
                ('Loan_Status', models.BooleanField()),
                ('Previous_Ded_Amount', models.FloatField()),
            ],
            options={
                'db_table': 'HR_Loans',
                'managed': False,
            },
        ),
    ]
