# Generated by Django 5.0.1 on 2024-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HR_GetUserMenuAndForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COID', models.IntegerField()),
                ('CoName', models.CharField(max_length=50)),
                ('User_ID', models.IntegerField()),
                ('User_Name', models.CharField(max_length=50)),
                ('FormID', models.IntegerField()),
                ('FormDescr', models.CharField(max_length=100)),
                ('ModuleID', models.IntegerField()),
                ('ModuleDescr', models.CharField(max_length=50)),
                ('MnuID', models.IntegerField()),
                ('MnuDescr', models.CharField(max_length=50)),
                ('MnuSubID', models.IntegerField()),
                ('MnuSubDescr', models.CharField(max_length=50)),
                ('FormSeq', models.IntegerField()),
                ('FormStatusID', models.IntegerField()),
                ('FormStatus', models.CharField(max_length=2)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
