"""
Django settings for HRMS project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/s
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jt_!3%s34cw86#@_+oa*1r+2(dlx4&5dk4zs=_lna^f)8fy(w)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    # 'bootstrap4',
    # 'report_builder'
]

#command create new api  
#py manage.py startapp salaryslip

EXTERNAL_APPS = [
    'city',
    'department',
    'designation',
    'grade',
    'salary_slip',
    'employee',
    # 'department',
    'leaves',
    'loan',
    'payroll_element',
    'payroll_period',   
    'salary_update',
    'hr_login',
    'dashboard',
    'administration',
    'working_dept_assignment',
    'monthly_all_ded',
    'monthly_sal_process',
    'monthly_payroll_sheet',
    # 'django_extensions',
]

INSTALLED_APPS += EXTERNAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'HRMS.middlewares.custom_middleware.BypassCSRFMiddleware',  # Insert this line
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8000',
    "http://localhost:8000",  # Add your frontend origin here
    "http://*",
    "https://*",
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

ROOT_URLCONF = 'HRMS.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # for app template files
        # 'DIRS': [],
        # for global template files
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HRMS.wsgi.application'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


SHELL_PLUS = "ipython"

DATABASES = {
    'default': {
        'ENGINE': 'mssql', 
        'NAME': 'ATS_HRMS',
        'USER': 'tech',
        'PASSWORD': 'tech',
        'HOST': '192.168.20.166', 
        'PORT': '1433',  # Leave it as an empty string for the default port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            # 'driver': 'ODBC Driver 18 for SQL Server',
            # 'extra_params': 'TrustServerCertificate=yes',
        },
    },
    # 'erp_admin': {
    #     'ENGINE': 'mssql',
    #     'NAME': 'ERP_ADMIN',
    #     'USER': 'tech',``
    #     'PASSWORD': 'tech',
    #     'HOST': '192.168.20.166',
    #     'PORT': '1433',  # Leave it as an empty string for the default port
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# # for app static files
# STATIC_URL = 'static/'

# # for global static files
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / "static" ]

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'myapp.middleware': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
