# Generated by Django 5.0.1 on 2024-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HR_FinYearMstr',
            fields=[
                ('FYID', models.AutoField(primary_key=True, serialize=False)),
                ('FinYear', models.CharField(max_length=20)),
                ('FYStatus', models.BooleanField()),
            ],
            options={
                'db_table': 'HR_FinYearMstr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HR_PAYROLL_MONTH',
            fields=[
                ('MNTH_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MNTH_NO', models.IntegerField()),
                ('MNTH_NAME', models.CharField(max_length=25)),
                ('MNTH_SHORT_NAME', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'HR_PAYROLL_MONTH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HR_PAYROLL_PERIOD',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PERIOD_ID', models.IntegerField()),
                ('PERIOD_STATUS', models.BooleanField()),
            ],
            options={
                'db_table': 'HR_PAYROLL_PERIOD',
                'managed': False,
            },
        ),
    ]
