# Generated by Django 5.0.1 on 2024-04-04 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('employee', '__first__'),
        ('grade', '0001_initial'),
        ('payroll_element', '0001_initial'),
        ('payroll_period', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Element_Grade_Combination',
            fields=[
                ('Combination_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Element_ID', models.ForeignKey(db_column='Element_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_element.hr_payroll_elements')),
                ('Grade_ID', models.ForeignKey(db_column='Grade_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grade.hr_grade')),
            ],
            options={
                'db_table': 'HR_Element_Grade_Combination',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HR_Monthly_All_Ded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic_Salary_1', models.IntegerField(blank=True, null=True)),
                ('Medical_Allowance_2', models.IntegerField(blank=True, null=True)),
                ('Conveyance_Allowance_3', models.IntegerField(blank=True, null=True)),
                ('Overtime_Allowance_4', models.IntegerField(blank=True, null=True)),
                ('House_Rent_Allowanc_5', models.IntegerField(blank=True, null=True)),
                ('Utilities_Allowance_6', models.IntegerField(blank=True, null=True)),
                ('Meal_Allowance_7', models.IntegerField(blank=True, null=True)),
                ('Arrears_8', models.IntegerField(blank=True, null=True)),
                ('Bike_Maintainence_9', models.IntegerField(blank=True, null=True)),
                ('Incentives_10', models.IntegerField(blank=True, null=True)),
                ('Device_Reimbursment_11', models.IntegerField(blank=True, null=True)),
                ('Communication_12', models.IntegerField(blank=True, null=True)),
                ('Bonus_13', models.IntegerField(blank=True, null=True)),
                ('Other_Allowance_14', models.IntegerField(blank=True, null=True)),
                ('Loan_15', models.IntegerField(blank=True, null=True)),
                ('Advance_Salary_16', models.IntegerField(blank=True, null=True)),
                ('EOBI_17', models.IntegerField(blank=True, null=True)),
                ('Income_Tax_18', models.IntegerField(blank=True, null=True)),
                ('Absent_Days_19', models.IntegerField(blank=True, null=True)),
                ('Device_Deduction_20', models.IntegerField(blank=True, null=True)),
                ('Over_Utilizaton_Mobile_21', models.IntegerField(blank=True, null=True)),
                ('Vehicle_or_Fuel_Deduction_22', models.IntegerField(blank=True, null=True)),
                ('Pandamic_Deduction_23', models.IntegerField(blank=True, null=True)),
                ('Late_Days_24', models.IntegerField(blank=True, null=True)),
                ('Other_Deduction_25', models.IntegerField(blank=True, null=True)),
                ('Mobile_Installment_26', models.IntegerField(blank=True, null=True)),
                ('Food_Panda_27', models.IntegerField(blank=True, null=True)),
                ('Department', models.ForeignKey(db_column='Dept_ID', on_delete=django.db.models.deletion.CASCADE, to='department.hr_department')),
                ('Employee', models.ForeignKey(db_column='Emp_ID', on_delete=django.db.models.deletion.CASCADE, to='employee.hr_employees')),
                ('Period', models.ForeignKey(db_column='Payroll_Period_ID', on_delete=django.db.models.deletion.CASCADE, to='payroll_period.hr_payroll_period')),
            ],
            options={
                'db_table': 'HR_Monthly_All_Ded',
                'managed': True,
            },
        ),
    ]
