# Generated by Django 5.0.1 on 2024-03-18 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '__first__'),
        ('payroll_period', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Monthly_All_Ded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic_Salary_01', models.IntegerField()),
                ('Medical_Allowance_02', models.IntegerField()),
                ('Conveyance_Allowance_03', models.IntegerField()),
                ('Overtime_Allowance_04', models.IntegerField()),
                ('House_Rent_Allowanc_05', models.IntegerField()),
                ('Utilities_Allowance_06', models.IntegerField()),
                ('Meal_Allowance_07', models.IntegerField()),
                ('Bike_Maintainence_08', models.IntegerField()),
                ('Device_Reimbursment_09', models.IntegerField()),
                ('Communication_10', models.IntegerField()),
                ('Bonus_11', models.IntegerField()),
                ('Other_Allowance_12', models.IntegerField()),
                ('Loan_13', models.IntegerField()),
                ('Advance_Salary_14', models.IntegerField()),
                ('EOBI_15', models.IntegerField()),
                ('Income_Tax_16', models.IntegerField()),
                ('Absent_Days_17', models.IntegerField()),
                ('Device_Deduction_18', models.IntegerField()),
                ('Over_Utilizaton_Mobile_19', models.IntegerField()),
                ('Vehicle_or_Fuel_Deduction_20', models.IntegerField()),
                ('Pandamic_Deduction_21', models.IntegerField()),
                ('Late_Days_22', models.IntegerField()),
                ('Other_Deduction_23', models.IntegerField()),
                ('Mobile_Installment_24', models.IntegerField()),
                ('Food_Panda_25', models.IntegerField()),
                ('Arrears_26', models.IntegerField()),
                ('Incentives_27', models.IntegerField()),
                ('Employee', models.ForeignKey(db_column='Emp_ID', on_delete=django.db.models.deletion.CASCADE, to='employee.hr_employees')),
                ('Period_ID', models.ForeignKey(db_column='Payroll_Period_ID', on_delete=django.db.models.deletion.CASCADE, to='payroll_period.hr_payroll_period')),
            ],
            options={
                'db_table': 'HR_Monthly_All_Ded',
                'managed': True,
            },
        ),
    ]
