# Generated by Django 5.0.1 on 2024-03-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_all_ded', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr_monthly_all_ded',
            old_name='Period_ID',
            new_name='Period',
        ),
    ]
