# Generated by Django 5.0.1 on 2024-04-03 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('monthly_all_ded', '0003_rename_absent_days_17_hr_monthly_all_ded_absent_days_19_and_more'),
        ('payroll_element', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Absent_Days_19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Advance_Salary_16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Arrears_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Basic_Salary_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Bike_Maintainence_9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Bonus_13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Communication_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Conveyance_Allowance_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Device_Deduction_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Device_Reimbursment_11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='EOBI_17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Food_Panda_27',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='House_Rent_Allowanc_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Incentives_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Income_Tax_18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Late_Days_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Loan_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Meal_Allowance_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Medical_Allowance_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Mobile_Installment_26',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Other_Allowance_14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Other_Deduction_25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Over_Utilizaton_Mobile_21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Overtime_Allowance_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Pandamic_Deduction_23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Utilities_Allowance_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr_monthly_all_ded',
            name='Vehicle_or_Fuel_Deduction_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HR_Payroll_Element_Grade',
            fields=[
                ('combination_id', models.AutoField(primary_key=True, serialize=False)),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_element.hr_payroll_elements')),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.hr_grade')),
            ],
            options={
                'db_table': 'HR_Payroll_Element_Grade',
                'managed': True,
            },
        ),
    ]
