# Generated by Django 5.0.1 on 2024-04-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('monthly_all_ded', '0004_alter_hr_monthly_all_ded_absent_days_19_and_more'),
        ('payroll_element', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HR_Payroll_Element_Grade',
            new_name='HR_Payroll_Grade_Combination',
        ),
    ]
