# Generated by Django 5.0.1 on 2024-04-03 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('monthly_all_ded', '0007_rename_hr_element_grade_hr_element_grade_combination_and_more'),
        ('payroll_element', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr_element_grade_combination',
            old_name='combination_id',
            new_name='Combination_ID',
        ),
        migrations.RemoveField(
            model_name='hr_element_grade_combination',
            name='element_id',
        ),
        migrations.RemoveField(
            model_name='hr_element_grade_combination',
            name='grade_id',
        ),
        migrations.AddField(
            model_name='hr_element_grade_combination',
            name='Element_ID',
            field=models.ForeignKey(db_column='Element_ID', default=None, on_delete=django.db.models.deletion.CASCADE, to='payroll_element.hr_payroll_elements'),
        ),
        migrations.AddField(
            model_name='hr_element_grade_combination',
            name='Grade_ID',
            field=models.ForeignKey(db_column='Grade_ID', default=None, on_delete=django.db.models.deletion.CASCADE, to='grade.hr_grade'),
        ),
    ]
