# Generated by Django 5.0.1 on 2024-04-03 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('monthly_all_ded', '0008_rename_combination_id_hr_element_grade_combination_combination_id_and_more'),
        ('payroll_element', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_element_grade_combination',
            name='Element_ID',
            field=models.ForeignKey(db_column='Element_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_element.hr_payroll_elements'),
        ),
        migrations.AlterField(
            model_name='hr_element_grade_combination',
            name='Grade_ID',
            field=models.ForeignKey(db_column='Grade_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.hr_grade'),
        ),
    ]
